title: tsubasaogawa.me
description: Whiteout Engineering

remote_theme: pages-themes/primer

plugins:
  - jekyll-feed
  - jekyll-remote-theme

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"