title: tsubasaogawa.me
description: Whiteout Engineering

remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-remote-theme

minima:
  skin: dark

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"